In [1]:
# 2d list: list of lists
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 3x3 matrix
for row in a:
    for col in row:
        print(col, end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


In [2]:
# print 2nd row
print(a[1])

[4, 5, 6]


In [3]:
# get number 6
print(a[1][2])

6


In [4]:
# slicing: same as 1d list
print(a[1:3])

[[4, 5, 6], [7, 8, 9]]


In [6]:
print(a[1])
print(a[1:2])

[4, 5, 6]
[[4, 5, 6]]


In [16]:
student_grades = [['John', 7.5], ['Mary', 9.0], ['Bob', 6.0], ['Alice', 8.0], ['Mike', 4.0],
                    ['Anna', 10.0], ['Tom', 5.0], ['Peter', 3.5], ['Jane', 9.5], ['Jack', 6.5]]

In [20]:
# Print distinction students who have the grade >= 8.0

for stu in student_grades:
    if stu[1] >= 8.0:
        print(f'{stu[0]:10s}:{stu[1]:10.0f}')

Mary      :         9
Alice     :         8
Anna      :        10
Jane      :        10


In [21]:
# Count how many passed student (grade >= 4.0)

count = 0
for stu in student_grades:
    if stu[1] >= 4.0:
        count += 1
print('Number of passed students: ', count)

Number of passed students:  9


In [ ]:
# length of rows can be different
a = [[],
    [1],
    [2, 3],
    [4, 5, 6]]
print(a, len(a))
print(a[3][2])
print(a[2][2]) # error: IndexError: list index out of range 

In [25]:
# Exercise
# Create 2d list 5x5 of random interger
# random
import random as rd
a = []
for i in range(5):
    a.append(rd.sample(range(0, 99), 5))
print(a)


[[92, 31, 38, 10, 42], [10, 33, 54, 59, 69], [30, 6, 23, 96, 56], [32, 52, 10, 72, 2], [41, 59, 3, 84, 22]]


In [28]:
# Get 3 middle rows in as many ways as you can

print(a[1], a[2], a[3])
print(a[-4], a[-3], a[-2])
print(a[1:4])
print(a[-4:-1])

[10, 33, 54, 59, 69] [30, 6, 23, 96, 56] [32, 52, 10, 72, 2]
[10, 33, 54, 59, 69] [30, 6, 23, 96, 56] [32, 52, 10, 72, 2]
[[10, 33, 54, 59, 69], [30, 6, 23, 96, 56], [32, 52, 10, 72, 2]]
[[10, 33, 54, 59, 69], [30, 6, 23, 96, 56], [32, 52, 10, 72, 2]]


In [31]:
# Get 2 last row in as many as you can

print(a[3], a[4])
print(a[-2], a[-1])
print(a[-2:])
print(a[3:])

[32, 52, 10, 72, 2] [41, 59, 3, 84, 22]
[32, 52, 10, 72, 2] [41, 59, 3, 84, 22]
[[32, 52, 10, 72, 2], [41, 59, 3, 84, 22]]
[[32, 52, 10, 72, 2], [41, 59, 3, 84, 22]]


In [37]:
# Enter n from keyboard, get max, min of nth row and print them (hint: using function max, min)

n = int(input('Enter n: '))
print('Max = ', max(a[n-1]))
print('Min = ', min(a[n-1]))

Max =  69
Min =  10


In [38]:
# Enter n from keyboard, get sum of nth row and print it (hint: using function sum)

n = int(input('Enter n: '))
print('Sum = ', sum(a[n-1]))

Sum =  225


In [44]:
# Enter n from keyboard, sort nth row and print it (hint: using function sorted)

n = int(input('Enter n: '))
print('Sorted = ', sorted(a[n-1]))
a[n-1].sort(reverse = True)
print('Sorted des = ', a[n-1])

Sorted =  [10, 33, 54, 59, 69]
Sorted des =  [69, 59, 54, 33, 10]


In [46]:
import numpy as np
# create array from list
a = [1, 2, 3]
b = np.array(a)
print(a, b, sep='\n')
print(a, type(a))
print(b, type(b))

[1, 2, 3]
[1 2 3]
[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [47]:
# Create a range from arange function (similar range function)
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [48]:
# Create array from linspace(start, end, n) function
a = np.linspace(0, 9, 9)
print(a)

[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875 9.   ]


In [50]:
# Create array from langspace(start, end, n) function
a = np.logspace(0, 10, 11, base=2, dtype=int)
print(a)

[   1    2    4    8   16   32   64  128  256  512 1024]


In [60]:
# Create array from 50 -100, step 5
a = np.arange(50, 101, 5)
print(a)

# Create 15 numbers from 2 to 5
b = np.linspace(2, 5, 15)
print(b)

# Create these numbers: 3, 9, 27, 81, 243, 729, 2187, 6561, 19683, 59049
c = np.logspace(1, 10, 10, base=3, dtype=int)
print(c)

[ 50  55  60  65  70  75  80  85  90  95 100]
[2.         2.21428571 2.42857143 2.64285714 2.85714286 3.07142857
 3.28571429 3.5        3.71428571 3.92857143 4.14285714 4.35714286
 4.57142857 4.78571429 5.        ]
[    3     9    27    81   243   729  2187  6561 19683 59049]


In [61]:
# Create arrays of zeros, one 
zeros = np.zeros(10)
print(zeros)
ones = np.ones((3,3))
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
# Array operator: +, -, *, /, %, //, ** with number
a = np.random.randint(0, 100, 5)
print(a)
print(a + 10)
print(a - 10)
print(a * 10)
print(a / 10)
print(a % 10)
print(a // 10)
print(a ** 2)


[31 35 28 54 74]
[41 45 38 64 84]
[21 25 18 44 64]
[310 350 280 540 740]
[3.1 3.5 2.8 5.4 7.4]
[1 5 8 4 4]
[3 3 2 5 7]
[ 961 1225  784 2916 5476]


In [68]:
# Array operator: +, -, *, /, %, //, ** with array (same size)
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)


[ 3  7 11]
[-1 -1 -1]
[ 2 12 30]
[0.5        0.75       0.83333333]
[1 3 5]
[0 0 0]
[    1    81 15625]


In [70]:
# Boolean indexing
a = np.random.randint(1, 100, 10)
b = a % 2 == 0
print(a)
print(b)
print(a[b])

[80 40 79 44 17 55 51  9 33  3]
[ True  True False  True False False False False False False]
[80 40 44]


In [73]:
# Find number that has the last digit is 3
a = np.random.randint(1, 100, 10)
b = a % 10 == 3
print(a)
print(b)
print(a[b])

[70 92 53 76 72 18 59 14 30 21]
[False False  True False False False False False False False]
[53]


In [75]:
# Find number that has the first digit is 5
a = np.random.randint(1, 100, 10)
b = a // 10 == 5
print(a)
print(b)
print(a[b])

[96 96 50 45 12 99 31 58 24 89]
[False False  True False False False False  True False False]
[50 58]


In [80]:
# Find numbers that has sum of digits > 10
a = np.random.randint(1, 100, 10)
b = a // 10
c = a % 10
print(a)
print(b)
print(c)
print(a[(a // 10 + a % 10) > 10])

[75 77 25 81 62 53 15 35 94  3]
[7 7 2 8 6 5 1 3 9 0]
[5 7 5 1 2 3 5 5 4 3]
[75 77 94]


In [82]:
#
# 2d Array indexing & slicing
a = np.random.randint(1, 100, (5, 5))
print(a)
# Indexing list-style
print(a[2][3])
# Indexing array-style
print(a[2, 3])

[[81  7 59 73 46]
 [63 81 63 26 97]
 [41 45 16 28 93]
 [82 12 49 80 14]
 [ 6 80 78 76 28]]
28
28


In [86]:
# Slice row
print(a[1:4])
# Slice columns
print(a[:, 1:3])
# Both
print(a[1:4, 1:3])

[[63 81 63 26 97]
 [41 45 16 28 93]
 [82 12 49 80 14]]
[[ 7 59]
 [81 63]
 [45 16]
 [12 49]
 [80 78]]
[[81 63]
 [45 16]
 [12 49]]


In [87]:
print(len(a), np.shape(a))

5 (5, 5)


In [92]:
b = a[0]
c = a[0:1, :]
print(b ,c)
print(np.shape(b), np.shape(c))

# Transpose c
d = c.T
print(d, np.shape(d))

[81  7 59 73 46] [[81  7 59 73 46]]
(5,) (1, 5)
[[81]
 [ 7]
 [59]
 [73]
 [46]] (5, 1)
