In [37]:
def my_max(a, b):
    if a > b:
        return a
    return b

In [ ]:
print(my_max(5, 7)) # work with integers
print(my_max('a', 'b')) # work with strings
print(my_max(5.0, 4.2)) # work with floats

In [ ]:
print(my_max(5.0, 5)) 

In [34]:
# pass by value vs pass by reference
def double(x):
    x = x * 2
    print(x)

In [38]:
x = 6
double(x) # => 12
print(x)  # => 6

12
6


In [35]:
import numpy as np
x = np.array([1, 2, 3])
double(x) # => [2 4 6]
print(x)  # => [1 2 3]

[2 4 6]
[1 2 3]


In [39]:
def double_list(x):
    for i in range(len(x)):
        x[i] = x[i] * 2
    print(x)

In [40]:
x = np.array([1, 2, 3])
double_list(x) # => [2 4 6]
print(x)  # => [2 4 6]

[2 4 6]
[2 4 6]


In [ ]:
print(4, 5, 6, sep='*')

In [32]:
def my_sort(a, asc=True):
    n = len(a)
    if asc:
        for i in range(n - 1):
            for j in range(i + 1, n):
                if a[j] < a[i]:
                    a[i], a[j] = a[j], a[i]
    else:
        for i in range(n - 1):
            for j in range(i + 1, n):
                if a[j] > a[i]:
                    a[i], a[j] = a[j], a[i]

In [41]:
numbers = [np.random.randint(0, 100) for i in range(10)]
print(numbers)
my_sort(numbers)
print(numbers)
my_sort(numbers, asc=False)
print(numbers)

[1, 79, 91, 76, 40, 72, 13, 61, 95, 17]
[1, 13, 17, 40, 61, 72, 76, 79, 91, 95]
[95, 91, 79, 76, 72, 61, 40, 17, 13, 1]


In [ ]:

def demo_keyword(x, n=10, s='hello'):
    print('x =', x)
    print('n =', n)
    print('s =', s)

In [ ]:
demo_keyword(5)

In [ ]:

demo_keyword(5, n='hello')

In [ ]:
demo_keyword(5, n='hello', s=10)

In [ ]:

demo_keyword('hi', s='hello python', n=100)

In [ ]:
print(3, 4, 5)
print()
print(10)

In [ ]:
def my_sum(*items):
    print(type(items))
    s = 0
    for i in items:
        s += i
    return s

In [ ]:

print(my_sum(1, 2, 3, 4.7, 5))

In [ ]:
def min_max(a, b):
    if a > b:
        return b, a
    return a, b

In [ ]:
mi, ma = min_max(50, 7)
print(mi, ma)

In [ ]:
_, ma = min_max(50, 7)
print(ma)

In [ ]:
m = min_max(50, 7)
print(m)

In [7]:
# Search for x in items, return the True if found, Flase otherwise. If abs = True, search for |x|
def search(items, x, abs=False):
    if x in items:
        print('True')
    elif abs == True:
        for i in items:
            if x == i or x == -i:
                return True
    else:
        print('False')
    
search([0, 1, 2, 3, 4, 5], 5)
search([0, 1, 2, 3, 4, -5], 5, abs =True)

True


True

In [10]:
def search2(items, x, abs=False):
    if abs == False:
        return x in items
    else:
        return x in items or -x in items

print(search2([0, 1, 2, 3, 4, 5], 5))
print(search2([0, 1, 2, 3, 4, -5], 5, abs =True))

True
True


In [43]:
def my_max(items, key=None):
    if key is None:
        m = items[0]
        for i in items:
            if i > m:
                m = 1
        return m
    else:
        m = items[0]
        for i in items:
            if key(i) > key(m):
                m = i
        return m

In [44]:
names = ['John Lennon', 'Mary Antoanette', 'Peter Dinglas', 'Alice Cooper']
m = my_max(names)
print(m)
m = my_max(names, key=len)
print(m)

TypeError: '>' not supported between instances of 'str' and 'int'

In [25]:
# Find name that has max last name
def last_name(name):
    return name.split()[-1]

m = my_max(names, key=last_name)
print(m)

John Lennon


In [29]:
# Find name that has max number of vowels
def vowel_count(name):
    vowels = 'aeiou'
    count = 0
    for c in name.lower():
        if c in vowels:
            count += 1
    return count

m = my_max(names, key=vowel_count)
print(m) 

Mary Antoanette


In [45]:
print(numbers)
print(my_max(numbers))

[95, 91, 79, 76, 72, 61, 40, 17, 13, 1]
95


In [46]:
# Find number that has max last digit
def digit(n):
    return n%10

print(my_max(numbers, key=digit))

79


In [54]:
# Find number that has max sum digits
def sum_digit(n):
    return n%10 + n//10 

print(my_max(numbers, key=sum_digit))

# Find numbet that has max absolute value
numbers = [np.random.randint(-100,100) for i in range(10)]
print(numbers)
def absolute(n):
    if n > 0:
        return n
    else:
        return n * -1

print(my_max(numbers, key=absolute))

73
[53, -75, -85, 20, -28, 73, -34, -56, 62, -40]
-85
