In [1]:
f = open('hello.py', 'r')
content = f.readlines()
print(content)

for line in content:
    print(line.strip())
f.close()

["print('Hello Python')"]
print('Hello Python')


In [2]:
with open('hello.py', 'r') as f:
    content = f.readlines()
    print(content)

["print('Hello Python')"]


In [3]:
# TODO: read egencies.txt, find all agencies that has Authority in name.
with open('Datasets/agencies.txt', 'r') as f:
    content = f.readlines()
    for line in content:
        if 'Authority' in line:
            print(line.strip())

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [4]:
# read agencies line by lne
try:
    with open('Datasets/agencies.txt', 'r') as f:
        line = f.readline()
        while line:
            if 'Authority' in line:
                print(line.strip())
            line = f.readline()
except FileNotFoundError:
    print('File not found')

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [5]:
# read agencies line by lne ALT
try:
    f = open('Datasets/agencies.txt', 'r')
    line = f.readline()
    while line:
        if 'Authority' in line:
            print(line.strip())
        line = f.readline()
    f.close()
except FileNotFoundError:
    print('File not found')

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [10]:
# TODO: count number of line & number of word in agencies.txt
try:
    cl = 0
    cw = 0
    f = open('Datasets/agencies.txt', 'r')
    line = f.readlines()

        
    cl = len(line)
    for content in line:
        cw += len(content.split())
    f.close()
    print(cl)
    print(cw)
except FileNotFoundError:
    print('File not found')

6
30


In [30]:
# TODO: read & print name, email of authors in authors.txt
# Example: Paul Bakaul: pault.bakaus@gmail.com

with open('Datasets/authors.txt', 'r') as f:
    line = f.readline()
    while line:
        if '@' in line:
            name, email = line.split('<')
            print(f'{name.strip():30}:{email.strip()[:-1]:>40}')
        line = f.readline()


Paul Bakaus                   :                   paul.bakaus@gmail.com
Richard Worth                 :                       rdworth@gmail.com
Yehuda Katz                   :                        wycats@gmail.com
Sean Catchpole                :                        sean@sunsean.com
John Resig                    :                       jeresig@gmail.com
Tane Piper                    :                    piper.tane@gmail.com
Dmitri Gaskin                 :                     dmitrig01@gmail.com
Klaus Hartl                   :                   klaus.hartl@gmail.com
Stefan Petre                  :                  stefan.petre@gmail.com
Gilles van den Hoven          :                      gilles@webunity.nl
Micheil Bryan Smith           :                 micheil@brandedcode.com
Jörn Zaefferer               :               joern.zaefferer@gmail.com
Marc Grabanski                :                     m@marcgrabanski.com
Keith Wood                    :                     kbwood@iinet

In [41]:
# Read falling.txt , store data into 3 list: times, heights, uncertainties
with open('Datasets/falling.txt', 'r') as f:
    times = []
    heights = []
    uncertainties = []
    for i in range(5):
        next(f)
    line = f.readline()
    while line:
        _, t, h, u = line.split()
        times.append(float(t))
        heights.append(float(h))
        uncertainties.append(float(u))
        line = f.readline()

print('Times: ', times)
print('Height: ', heights)
print('Uncertainties: ', uncertainties)

import numpy as np
data = np.loadtxt('Datasets/falling.txt',      # File name
                                            skiprows=5,                 # skip 5 first lines
                                            usecols=(1,2,3))            # use colums 1, 2, 3
print(data)

Times:  [0.0, 0.5, 0.7]
Height:  [180.0, 185.0, 192.0]
Uncertainties:  [3.5, 4.5, 5.2]
[[  0.  180.    3.5]
 [  0.5 185.    4.5]
 [  0.7 192.    5.2]]


In [67]:
# TODO: read grades.txt, print Distinction students (average >= 8.0)
data = np.loadtxt('Datasets/grades.txt', skiprows=5, dtype=str)
print(data)

# 1
print('Distinction students: ', [row[0] for row in data if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0 ])

# 2
for row in data:
    if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0:
        print(f'{row[0]:<15}:{(float(row[1]) + float(row[2]) + float(row[3]))/3:10.3f}')

# 3
names, maths, liters, english = np.loadtxt('Datasets/grades.txt', skiprows=5, dtype=str, unpack=True)
for i in range(len(names)):
    if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0:
        print(name[i], end=' ')

# 4
for name in ([row[0] for row in data if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0 ]):
    print(name, end=' ')

# 5
    # 
    


    

SyntaxError: invalid syntax (546438281.py, line 24)

In [70]:
# Read csv file usgin numpy.loadtxt
codes, names, grades = np.loadtxt('Datasets/gradebook.csv', delimiter=',', skiprows=1, usecols=(2, 3, 4), dtype=str, unpack=True)
for i in range(len(codes)):
    print(f'{codes[i]}:{names[i]}, {grades[i]}')

GBH17538:Le Minh Huong, 6.5
GCH16025:Bui Phuong Nam, 0
GCH16336:Nguyen The Dat, 6.5
GCH16388:Pham Minh Thang, 6.5
GCH16573:Do Duy Tung, 6.5


In [2]:
fr = open('Datasets/agencies.txt', 'r')
content = fr.readlines()

fw = open('Datasets/agency_authority.txt', 'w')
for line in content:
    if 'Authority' in line:
        print(line.strip())
        fw.write(line.strip() + '\n')
print('authority agencies have been saved!')
fr.close()
fw.close()

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey
authority agencies have been saved!


In [7]:
import numpy as np
names, maths, liters, english = np.loadtxt('Datasets/grades.txt', skiprows=5, dtype=str, unpack=True)
merits = [['Name', 'Math', 'Literature', 'English']]
for i in range(len(names)):
    if (float(maths[i]) + float(liters[i]) + float(english[i])) / 3 >= 8.0:
        print(names[i])
        merits.append([names[i], maths[i], liters[i], english[i]])

np.savetxt('Datasets/merits.csv', merits, fmt='%s', delimiter=',')

Lan
Hung


In [8]:
import csv
fw = open('Datasets/gradebook_pass.csv', 'w')
writer = csv.writer(fw)
writer.writerow(['Login', 'Email', 'Code', 'Name', 'Grade'])
with open('Datasets/gradebook.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        if float(row[4]) >= 6.5:
            print(f'{row[2]}:{row[3]}, {row[4]}')
            writer.writerow(row)
fw.close()

GBH17538:Le Minh Huong, 6.5
GCH16336:Nguyen The Dat, 6.5
GCH16388:Pham Minh Thang, 6.5
GCH16573:Do Duy Tung, 6.5


In [38]:
import csv
fw = open('Datasets/pizza_clean.csv', 'w')
writer = csv.writer(fw)
# writer.writerow(['id', 'address', 'categories', 'city', 'country', 'keys', 'latitude', 'longitude', 'menuPageURL', 'menus.amountMax', 'menus.amountMin', 
#                  'menus.currency', 'menus.dateSeen', 'menus.description', 'menus.name', 'name', 'postalCode', 'priceRangeCurrency', 'priceRangeMin', 'priceRangeMax',
#                  'province'])

with open('Datasets/pizza_data.csv', 'r') as f:
    reader = csv.reader(f)
    header = next(reader)
    del header[0]
    del header[7]
    for row in reader:
        if row[9] != '' and row[10] != '' and row[18] != '' and row[19] != '':
            row[2] = row[2].split(',')[0].split('/')[0].split('and')[0]
            del row[0]
            del row[7]
            writer.writerow(header)
            writer.writerow(row)
        



fw.close()